### ISSUE TITLE
The dependencies for the FAST input fields evaluate to be true from the FAST schema but they are not displayed on BIG-IP FAST form

### ISSUE THREAD

**Issue by selinaarokiaswamy-GSLAB** [F5Networks/f5-appsvcs-templates#83] opened 2021-11-02 11:39 UTC
### Environment
 * FAST RPM Version: 1.13.0
 * BIG-IP Version: 15.1.2.1

### Summary
The dependencies for the following FAST input fields evaluate to be true from the FAST schema but they are not displayed on BIG-IP FAST form. Please refer below images for reference.
FAST input fields :
1. SNMP Community String - Microsoft Exchange Template
2. Specify the name of an existing BIG-IP SSL certificate bundle that contains your chain of trust - Microsoft Exchange Template
3. Specify the name of an existing BIG-IP serverssl profile - Microsoft Exchange Template

<img width="920" alt="issue 3 fast schema" src="https://user-images.githubusercontent.com/88710971/139805640-26d0b277-45fa-4417-8dab-f50c7e0cd028.png">

### Steps To Reproduce
1. Go to iApps->Application Services -> Applications Lx -> F5 Application Services Templates 
2. Select any one of the above templates
3. Compare the input fields with the FAST schema
4. To view FAST Schema, Go to bottom of the page and expand Debug view
5. Click on Schema Tab from Debug view

### Expected Behavior
If the dependencies for the above FAST input fields evaluate to be true from the FAST schema then those fields should be displayed on BIG-IP FAST form

### Actual Behavior
The FAST input fields with valid dependencies should be displayed on BIG-IP FAST form

**Comment by shyawnkarim** [comment] 2021-11-05 16:42
Thanks for reporting this issue. We are now tracking it internally with ID MYSTIQUE-473.

**Comment by shyawnkarim** [comment] 2021-11-23 22:54
After taking a look at this, we were able to reproduce #1 but not able to reproduce #2 or #3.

- We will add the SNMP community string with a default value of 'public' to the Exchange template.
- Regarding #2 and #3, in version 15.1.3.1:
 		- the "TLS Server Chain" file lists does display when "TLS Server Chain" box is checked
 		- the "TLS Client Profile" list does display when the "TLS Client" box is checked and the "Automatically manage the TLS client profile" box isn't checked.

**Comment by selinaarokiaswamy-GSLAB** [comment] 2021-12-02 09:08
> After taking a look at this, we were able to reproduce point 1 but not able to reproduce points 2 and 3.
> 
> * We will add the SNMP community string with a default value of 'public' to the Exchange template.
> * Regarding points 2 and 3, in version 15.1.3.1:
>   - the "TLS Server Chain" file lists does display when "TLS Server Chain" box is checked
>   - the "TLS Client Profile" list does display when the "TLS Client" box is checked and the "Automatically manage the TLS client profile" box isn't checked.

@shyawnkarim Yes points 2 & 3 do display when "TLS Server Chain" & "TLS Client" boxes are checked, however the "TLS Server Chain" & "TLS Client" fields are of boolean type and do not have a default property, and so at some places in other templates (for example: Enable bluegreen field in BlueGreen Template) the fields that are of type boolean and do not have a default property were assumed to be true (or checked) by default. Hence, I think either "TLS Server Chain" & "TLS Client" should be checked by default which would display points 2 & 3 on the FAST form or add a default property to the above fields. Thanks.

**Comment by shyawnkarim** [comment] 2021-12-14 23:39
The BlueGreen template did not have default values for those check boxes, in schema, but they evaluated to true because the template used parameters to assign their initial value to true. This we call a pre-filled/example default. Without this entry in parameters, it would be unchecked initially - since there is no default in schema or prep-filled/example default in schema or prep-filled/example default in parameters. Here is a screenshot:

<img width="642" alt="Screen Shot 2021-12-14 at 3 36 49 PM" src="https://user-images.githubusercontent.com/4108719/146096459-4c9f9a10-210c-4973-85bd-b933c7a3ef14.png">

We are intentionally not giving these an initial value in schema or parameters, and that might be all he wants to know, but here are the reasons why these default values are intentionally not true:

1. TLS Server chain is not necessary or required, and it is commonly not used
2. TLS Client is unchecked because we are intentionally defaulting to SSL Offload, the customer does have to check this box if instead of the default settings, they would like to use SSL Bridging.

**Comment by shyawnkarim** [comment] 2021-12-14 23:43
Closing.

This issue was resolved with [Release 1.14.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.14.0).

**Closed** 2021-12-14 23:43 UTC
Labels: bug
