### ISSUE TITLE
validation error using nested parameters

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-appsvcs-templates#29] opened 2020-11-24 22:41 UTC
### Environment
 * FAST RPM Version: 1.5.0
 * BIG-IP Version: 15.1.2

### Summary
Unable to nest parameters unless you have more than one loop

### Steps To Reproduce
Create a nested templated
```
title: nested test
description: nested test
definitions:
  parent:
    title: parent
    description: parent
    type: array
  child:
    title: child
    description: child
parameters:
  parent: ["1","2","3"]
  child: hello

template: |
    {{ #parent }} {{ . }} {{ child }}{{ /parent }}
```
error
```
Failed to render template:
Error: Parameters failed validation:
{}

Validation error:
[
  {
    "keyword": "type",
    "dataPath": ".parent[0]",
    "schemaPath": "#/properties/parent/items/type",
    "params": {
      "type": "object"
    },
    "message": "should be object"
  }
]
    at Template.validateParameters (/home/erchen/projects/fast/node_modules/@f5devcentral/f5-fast-core/lib/template.js:910:19)
    at Template.render (/home/erchen/projects/fast/node_modules/@f5devcentral/f5-fast-core/lib/template.js:948:18)
    at /home/erchen/projects/fast/node_modules/@f5devcentral/f5-fast-core/cli.js:97:26
```
workaround
```
title: nested test
description: nested test
definitions:
  parent:
    title: parent
    description: parent
    type: array
  child:
    title: child
    description: child
parameters:
  parent: ["1","2","3"]
  child: hello

template: |
    {{ #parent }} {{ . }} {{ child }}{{ /parent }}
    {{ #parent }} {{ . }} {{ /parent }}
```
output
```
 1 hello 2 hello 3 hello
 1  2  3

```
### Expected Behavior
ability to use nested elements in a single loop
### Actual Behavior
error output

**Comment by shyawnkarim** [comment] 2021-02-18 18:01
Thanks for reporting this issue. We are now tracking this bug internally with ID MYSTIQUE-342.

**Comment by mstokes-f5** [comment] 2021-07-01 21:00
This appears to be working as intended. Variables found inside of a section are scoped to that section. In this case, FAST is looking for ``parent`` to be an array of objects with the properties ``.`` and ``child``. Passing in an array of strings is indeed not valid. Something like this would work:

``
parameters:
  parent:
    - .: 1
      child: hello
    - .: 2
      child: hello
    - .: 3
      child: hello
``

However, FAST does not currently provide a way to say a variable/parameter should be pulled from a global scope versus the local section's scope.

**Comment by shyawnkarim** [comment] 2021-08-31 20:25
Closing. Please reopen if this continues to be an issue for you.

**Closed by shyawnkarim** 2021-08-31 20:25 UTC
Labels: bug
