### ISSUE TITLE
FAST rewrite object stored in /$tenant/Shared

### ISSUE THREAD

**Issue by BenEkpy** [F5Networks/f5-appsvcs-templates#20] opened 2020-08-19 17:16 UTC
### Environment
 * FAST RPM Version: 1.2.0
 * BIG-IP Version: 15.1.0.4

### Summary
AS3 Shared applications can be used to stored shared object between applications of a tenant such as profile, irules, pool etc 

When FAST Templates is used to manage these objects (pool in my exemple), it rewrite all the contents of the Shared Application.

This is the default behavior of AS3 + FAST, all applications are overwritten, but It shouldn't be like that for Shared Applications if FAST tend to manage Shared Objects.

FAST should "patch" Shared Application like it does for tenants.

### Steps To Reproduce

1. Create a template to manage pool in the /Common/Shared 

```
# my_template_set/shared_pool.mst file

{
  "class": "ADC",
  "schemaVersion": "3.19.0",
  "Common": {
    "class": "Tenant",
    "Shared": {
      "class": "Application",
      "template": "shared",
      "{{pool_name}}": {
        "class": "Pool",
        "monitors": [
          "http"
        ],
        "members": [
          {
            "servicePort": {{server_port::integer}},
            "serverAddresses": {{server_addresses::array}}
          }
        ]
      }
    }
  }
}
```

2. Deploy a first pool with rest call to the FAST API

```
POST /mgmt/shared/fast/applications

 {
    "name": "my_first_template_set/shared_pool",
    "parameters": {
        "pool_name": "pool_1",
        "server_port": 80,
        "server_addresses": [
            "2.2.2.1"
        ]
    }
}
```

3. Deploy a second pool with rest call to the FAST API

_**POST /mgmt/shared/fast/applications**_

```
POST /mgmt/shared/fast/applications

 {
    "name": "my_first_template_set/shared_pool",
    "parameters": {
        "pool_name": "pool_2",
        "server_port": 80,
        "server_addresses": [
            "2.2.2.2"
        ]
    }
}
```

### Expected Behavior

Both pool created should be present on the Shared application.

```
> tmsh list ltm pool Shared/*

ltm pool Shared/pool_1 {
    members {
        Shared/2.2.2.1:http {
            address 2.2.2.1
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { http }
}
ltm pool Shared/pool_2 {
    members {
        Shared/2.2.2.2:http {
            address 2.2.2.2
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { http }
}
```

### Actual Behavior

The first pool "pool_1" previously declared is overwritten by the second declaration of "pool_2"
 
```
> tmsh list ltm pool Shared/*


ltm pool Shared/pool_2 {
    members {
        Shared/2.2.2.2:http {
            address 2.2.2.2
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { http }
}
```

Whatever the content of /$tenant/Shared, the last declaration overwritten everything.

**Comment by de1chk1nd** [comment] 2020-08-28 11:48
ran into the same issue (with certificates). Would be great to get a bugfix for this soon ;)

**Comment by zinkem5** [comment] 2020-08-28 14:24
This is working as intended, FAST is still declarative on a per-application basis. The "Shared" application in your template will be overwritten each time you deploy it in this way.

To create additional pools, you would want to template out the Application name of the template so you can create a new application. By using a new application name each time, a new pool will be created. 

{
  "class": "ADC",
  "schemaVersion": "3.19.0",
  "Common": {
    "class": "Tenant",
    "**{{application_name}}**": {
      "class": "Application",
      "template": "shared",
      "{{pool_name}}": {
        "class": "Pool",
        "monitors": [
          "http"
        ],
        "members": [
          {
            "servicePort": {{server_port::integer}},
            "serverAddresses": {{server_addresses::array}}
          }
        ]
      }
    }
  }
}

If you wanted to create multiple pools, you

**Comment by zinkem5** [comment] 2020-08-28 14:41
One last note, the previous examples have a fixed tenant of "Common", the Tenant name also needs to be templated if this template is intended to be deployed to tenants other than Common.

**Comment by BenF5** [comment] 2020-09-07 15:29
I think you're right, it works as intended, so it's more an RFE.

As describe in the AS3 Schema, Shared application, in a tenant, holds objects that other applications can share within the tenant (Common to be shared accross tenants).

It's the only way to share objects (created with AS3) within applications.

So Shared application should be an exception and not be work on a per-application basis, it should work on a per-object basis to be able to easily add new objects

Why ? so you don't have to declare all the object in the Shared Application each time you want to add an other object.

Most of F5 users want to reduce the number of object stored in the BIGIP as too much object have a negative impact on the control plane performance (and it's more relevant when you use automation)

To do so, they might store differents object in the Shared application such as ssl profile, http profile, analytics profile ... and even pool.

Some of my customer are using the same pool (with url routing) for lots of theur applications and they don't want to recreate this pool for each application they create.

So FAST with a per-object approch in the Shared Application would be nice :)


PS : When you use the shared template (in Common or other partition), you can't overwrite the application name Shared (so your first declaration isn't working)

**Comment by mstokes-f5** [comment] 2020-11-20 20:04
Please feel free to correct me on this, but I am not certain that it makes sense for an application deployed through FAST to modify the shared objects in this fashion. If the object is truly intended to be shared among multiple applications, I would think that shared object would be setup prior to deploying applications with FAST.

**Comment by shyawnkarim** [comment] 2021-11-05 21:08
Closing. Please reopen if needed.

**Closed** 2021-11-05 21:08 UTC
Labels: enhancement
